[package]
name = "iot_tracker"
version = "0.1.0"
authors = ["Tim Burrows <tburrows90@gmail.com>"]
edition = "2021"
publish = false

[workspace]
members = [".", "app", "data", "entities", "migration"]

[dependencies]
iot-tracker-app = { path = "app" }