//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;
use serde::{Serialize, Deserialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "device")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::device_interactions::Entity")]
    DeviceInteractions,
}

impl Related<super::device_interactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceInteractions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
